steps:
  # Create environment variables for the build
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
    - 'DISCORD_TOKEN=${_DISCORD_TOKEN}'
    - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
    - 'CLIENT_ID=${_CLIENT_ID}'
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/joi:$COMMIT_SHA', '.']
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/joi:$COMMIT_SHA']
